### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ariksa** [kbilsted/NppPluginRebaseAssister#1]
Although it says "moving lines up/down (`Ctrl `+ `Up `or `Down`)", it is actually `Ctrl + Shift`

**Comment by JacobBerlin** [comment]
Ctrl + Up or Down works fine for me. Ctrl + Shift + Up or Down is the default shortcut for moving lines in NPP, so that also works.

**Comment by kbilsted** [comment]
yup
